### ISSUE TITLE
License and deps issues

### ISSUE THREAD

**Issue by tkittel** [McStasMcXtrace/mccode-antlr#89]
While working on a conda-forge recipe for mccode-antlr with @willend, we discovered a few issues:

- No LICENSE file in the repo. For now we wrote BSD-3-Clause in the packaging meta data, but needs to be clarified. And conda-forge packages always needs a LICENSE file.
- The pyproject.toml specifies >=py3.9, but specifies deps for <py3.8 which could be cleaned up.
- The pinned dependency antlr4-python3-runtime==4.13.2 seems like it will give a lot of potential issues in a mcstas conda env. Could it be lifted please?

**Comment by g5t** [comment]
As part of #91 these issues have been addressed. Feel free to re-open this issue if you find that anything is lingering.
